### ISSUE TITLE
ListField(ReferenceField) appends ignored if empty array passed into constructor

### ISSUE THREAD

**Issue by joeshaw** [hmarr/mongoengine#355]
If you pass an empty list into the constructor of a Document with a `ListField(ReferenceField(...))`, it is never successfully appended.

```
class Foo(Document):
    bars = ListField(ReferenceField("Bar"))

class Bar(Document):
    text = StringField()

bar = Bar(text="hi")
bar.save()

foo = Foo(bars=[])
foo.bars.append(bar)

print foo.bars # => []

foo.bars.append(bar)

print foo.bars  # => [] -- doesn't matter how many times you try

foo = Foo()
foo.bars.append(bar)

print foo.bars  # => [<Bar: Bar object>]
```

**Comment by maxcountryman** [comment]
+1 I have this same issue. Actually quite a problem when you're not expecting it...

**Comment by rozza** [comment]
Fixed in dev branch :)

**Comment by travischoma** [comment]
There is a related issue that still exists if you set the property to the empty list ie foo.bars = []  . Subsequent appends will fail silently.
